workflows:
  build:
    name: Build for Android
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
